// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
      return 
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJdtCs7R5AhwbwiCZateQiDOymlI_vtO0',
    appId: '1:986922103626:web:c7455a6c44458e0c8207b3',
    messagingSenderId: '986922103626',
    projectId: 'mydalell-backend-project',
    authDomain: 'mydalell-backend-project.firebaseapp.com',
    storageBucket: 'mydalell-backend-project.appspot.com',
    measurementId: 'G-KFZ23W101W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj6G8cKbZum-7RWpmH3RKmShYsqZiWE7o',
    appId: '1:986922103626:android:266ae832f81de9838207b3',
    messagingSenderId: '986922103626',
    projectId: 'mydalell-backend-project',
    storageBucket: 'mydalell-backend-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjR3DXImC7CCqhdWbmC9RcWSRVohyTM0s',
    appId: '1:986922103626:ios:3e2c1a40db40a1818207b3',
    messagingSenderId: '986922103626',
    projectId: 'mydalell-backend-project',
    storageBucket: 'mydalell-backend-project.appspot.com',
    iosBundleId: 'com.wahel.dalell',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjR3DXImC7CCqhdWbmC9RcWSRVohyTM0s',
    appId: '1:986922103626:ios:3e2c1a40db40a1818207b3',
    messagingSenderId: '986922103626',
    projectId: 'mydalell-backend-project',
    storageBucket: 'mydalell-backend-project.appspot.com',
    iosBundleId: 'com.wahel.dalell',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJdtCs7R5AhwbwiCZateQiDOymlI_vtO0',
    appId: '1:986922103626:web:7f5cfdd30085de158207b3',
    messagingSenderId: '986922103626',
    projectId: 'mydalell-backend-project',
    authDomain: 'mydalell-backend-project.firebaseapp.com',
    storageBucket: 'mydalell-backend-project.appspot.com',
    measurementId: 'G-709PF2GGE9',
  );
}
